#!/usr/bin/env bash
# build-frontend.sh — Pull config from SSM and build the React dashboard.
#
# Usage:
#   bash scripts/build-frontend.sh --env dev
#   bash scripts/build-frontend.sh --env prod
#
# Prerequisites:
#   - AWS CLI configured with credentials that have ssm:GetParameter on
#     /radius/<env>/cognito/* and /radius/<env>/api/*
#   - Node.js 18+ and npm installed
#   - Infrastructure already deployed (infra values must exist in SSM)

set -euo pipefail

# ---------------------------------------------------------------------------
# Windows/WSL2 compatibility
# ---------------------------------------------------------------------------
_winpath() {
  local p="$1"
  if [[ "$p" =~ ^/mnt/([a-z])/(.*)$ ]]; then
    echo "${BASH_REMATCH[1]^^}:\\${BASH_REMATCH[2]//\//\\}"
  else
    echo "$p"
  fi
}

if ! command -v aws &>/dev/null && command -v aws.exe &>/dev/null; then
  aws() {
    local a=()
    for x in "$@"; do a+=("$(_winpath "$x")"); done
    aws.exe "${a[@]}" | tr -d '\r'
  }
  export -f aws _winpath
fi

if ! command -v npm &>/dev/null && command -v npm.cmd &>/dev/null; then
  npm() { npm.cmd "$@"; }
  export -f npm
fi

ENV=""
REGION="us-east-1"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --env)    ENV="$2";    shift 2 ;;
    --region) REGION="$2"; shift 2 ;;
    *) echo "Unknown argument: $1"; exit 1 ;;
  esac
done

if [[ -z "$ENV" ]]; then
  echo "ERROR: --env is required (dev or prod)"
  exit 1
fi

echo "==> Fetching config from SSM [env=${ENV}, region=${REGION}]"

get_param() {
  aws ssm get-parameter \
    --name "$1" \
    --region "${REGION}" \
    --query "Parameter.Value" \
    --output text
}

USER_POOL_ID=$(get_param "/radius/${ENV}/cognito/user_pool_id")
CLIENT_ID=$(get_param "/radius/${ENV}/cognito/client_id")
API_URL=$(get_param "/radius/${ENV}/api/endpoint")

echo "    USER_POOL_ID : ${USER_POOL_ID}"
echo "    CLIENT_ID    : ${CLIENT_ID}"
echo "    API_URL      : ${API_URL}"

ENV_FILE="frontend/.env.production"
cat > "${ENV_FILE}" << EOF
# Auto-generated by build-frontend.sh — do not edit manually.
# Source of truth is SSM Parameter Store (/radius/${ENV}/*).
VITE_API_BASE_URL=${API_URL}
VITE_COGNITO_USER_POOL_ID=${USER_POOL_ID}
VITE_COGNITO_CLIENT_ID=${CLIENT_ID}
EOF

echo "==> Written ${ENV_FILE}"

echo "==> Installing frontend dependencies"
npm --prefix frontend ci

echo "==> Building frontend"
npm --prefix frontend run build

echo "==> Build complete — output in frontend/dist/"
